// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkbsgndghdbbqfyaieyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrYnNnbmRnaGRiYnFmeWFpZXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTUxODEsImV4cCI6MjA2MTI3MTE4MX0.ccTgSa2mwY_OlLJdImjmc0MeEoaU45K9KwCaPeyabVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);